### ISSUE TITLE
Bugs with MSG

### ISSUE THREAD

**Issue by partydragen** [didjee2/BungeeUtilisals#18]
msg some times being bugged its stand %sender% it was not that on started but after using it for some mins its started to be me -> %sender%
And maybe fix when them are muted them can't use global msg/reply commands?

And a another bug when people are muted some commands being blocked :/ I don't want that

And fix so staff don't need to enabled /gspy every time we login.... Fix so its being saved idk how but BungeeEssentials had it but idk how

**EDIT:** 
Bugs: MSG Aliases being registred as reply commands :/
And Reply Aliases not working

example when i use /gtell that are in MSG Aliases

Its coming Please use /greply (message)! or You have nobody to reply to!
When i msged to my self them worked as Reply commands :/

**Comment by didjee2** [comment]
That bug about %sender% is in the Reply section in the config, replace %sender% in the message by %player%. I'll change the default config for that.

About blocking commands while muted, that's easy, just add them in the 'Blocked-Cmds-While-Muted' list. ([Screen](https://gyazo.com/7cb172d7da556d74c1ab2cdf7b1206ea)).

That MSG aliases bug is fixed in BungeeUtilisals [version 220](https://www.spigotmc.org/resources/bungeeutilisals.7865/update?update=105028).
